import { afterEach, describe, expect, it, vi } from 'vitest';
import { PuzzleStagla } from '../../src/puzzles/puzzle-stagla';

vi.mock('../../src/audio', () => ({
    playTone: vi.fn(),
    playChime: vi.fn(),
    playMelody: vi.fn().mockResolvedValue(undefined),
    initAudioOnFirstClick: vi.fn(),
}));

vi.mock('../../src/puzzles/shared', async () => ({
    ...(await vi.importActual('../../src/puzzles/shared')),
    sleep: vi.fn().mockResolvedValue(undefined),
}));

describe('puzzle-stagla', () => {
    afterEach(() => {
        document.body.innerHTML = '';
        vi.restoreAllMocks();
    });

    it('custom element is defined', () => {
        const el = document.createElement('puzzle-stagla');
        expect(el).toBeInstanceOf(PuzzleStagla);
    });

    it('creates 3 circles, 4 lights, and 4 labels', async () => {
        const el = document.createElement('puzzle-stagla') as PuzzleStagla;
        document.body.appendChild(el);
        await el.updateComplete;

        const top = el.querySelector('#stagla-top');
        expect(top).not.toBeNull();

        const circles = el.querySelectorAll('.stagla-circle');
        expect(circles.length).toBe(3);

        const lights = el.querySelectorAll('.stagla-light');
        expect(lights.length).toBe(4);

        const labels = el.querySelectorAll('.stagla-label');
        expect(labels.length).toBe(4);
    });

    it('labels show A, B, C, D', async () => {
        const el = document.createElement('puzzle-stagla') as PuzzleStagla;
        document.body.appendChild(el);
        await el.updateComplete;

        const labels = el.querySelectorAll('.stagla-label');
        expect(labels[0].textContent!.trim()).toBe('A');
        expect(labels[1].textContent!.trim()).toBe('B');
        expect(labels[2].textContent!.trim()).toBe('C');
        expect(labels[3].textContent!.trim()).toBe('D');
    });

    it('dispatches puzzle-status after creation', async () => {
        const el = document.createElement('puzzle-stagla') as PuzzleStagla;
        const statusSpy = vi.fn();
        el.addEventListener('puzzle-status', statusSpy);
        document.body.appendChild(el);
        await el.updateComplete;

        expect(statusSpy).toHaveBeenCalledWith(
            expect.objectContaining({
                detail: expect.objectContaining({ moves: 0 }),
            }),
        );
    });

    it('dispatches puzzle-actions on creation', async () => {
        const el = document.createElement('puzzle-stagla') as PuzzleStagla;
        const actionsSpy = vi.fn();
        el.addEventListener('puzzle-actions', actionsSpy);
        document.body.appendChild(el);
        await el.updateComplete;

        expect(actionsSpy).toHaveBeenCalledWith(
            expect.objectContaining({
                detail: expect.arrayContaining([
                    expect.objectContaining({ label: 'New Puzzle' }),
                    expect.objectContaining({ label: 'Reset' }),
                ]),
            }),
        );
    });

    it('clicking a light dispatches puzzle-status with incremented moves', async () => {
        const el = document.createElement('puzzle-stagla') as PuzzleStagla;
        document.body.appendChild(el);
        await el.updateComplete;

        const statusSpy = vi.fn();
        el.addEventListener('puzzle-status', statusSpy);

        const lights = el.querySelectorAll<HTMLDivElement>('.stagla-light');
        lights[0].click();
        await el.updateComplete;

        expect(statusSpy).toHaveBeenCalledWith(
            expect.objectContaining({
                detail: expect.objectContaining({ moves: 1 }),
            }),
        );
    });

    it('regenerate event triggers puzzle reset', async () => {
        const el = document.createElement('puzzle-stagla') as PuzzleStagla;
        document.body.appendChild(el);
        await el.updateComplete;

        const statusSpy = vi.fn();
        el.addEventListener('puzzle-status', statusSpy);

        el.dispatchEvent(new CustomEvent('puzzle-regenerate'));
        await el.updateComplete;

        expect(statusSpy).toHaveBeenCalledWith(
            expect.objectContaining({
                detail: expect.objectContaining({ moves: 0 }),
            }),
        );
    });

    it('all 3 circles light up as each stage completes (regression: 3rd circle)', async () => {
        const el = document.createElement('puzzle-stagla') as PuzzleStagla;
        document.body.appendChild(el);
        await el.updateComplete;

        // Read initial states and targets generated by the puzzle
        const stageInitialStates = (el as any)._stageInitialStates as boolean[][];
        const stageTargets = (el as any)._stageTargets as number[];

        const TOGGLES: number[][] = [[0, 1], [0, 1, 2], [1, 2, 3], [2, 3]];

        // Brute-force the solution for a given stage's lights and target
        function solveStage(lights: boolean[], target: number): number[] {
            for (let mask = 0; mask < 16; mask++) {
                const result = [...lights];
                for (let b = 0; b < 4; b++) {
                    if (mask & (1 << b)) {
                        for (const t of TOGGLES[b]) result[t] = !result[t];
                    }
                }
                let valid = true;
                for (let i = 0; i < 4; i++) {
                    if (i === target && !result[i]) valid = false;
                    if (i !== target && result[i]) valid = false;
                }
                if (valid) {
                    const seq: number[] = [];
                    for (let b = 0; b < 4; b++) if (mask & (1 << b)) seq.push(b);
                    return seq;
                }
            }
            return [];
        }

        const solutions = [
            solveStage(stageInitialStates[0], stageTargets[0]),
            solveStage(stageInitialStates[1], stageTargets[1]),
            solveStage(stageInitialStates[2], stageTargets[2]),
        ];

        for (const seq of solutions) {
            expect(seq.length).toBeGreaterThan(0);
        }

        // Solve each stage and verify its circle turns on
        for (let stage = 0; stage < 3; stage++) {
            const staglaLights = el.querySelectorAll('.stagla-light');
            for (const idx of solutions[stage]) {
                staglaLights[idx].click();
            }

            // Wait for stage completion to process (sleep is mocked to resolve instantly)
            await el.updateComplete;
            await new Promise(r => setTimeout(r, 0));

            const circles = el.querySelectorAll('.stagla-circle');
            for (let c = 0; c <= stage; c++) {
                expect(circles[c].classList.contains('on')).toBe(true);
            }
        }
    });
});
